In [1]:
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggnewscale)
library(ggplot2)
library(scales)

ERROR: Error in library(clusterProfiler): there is no package called ‘clusterProfiler’

In [2]:
emci_de <- read.csv("RP_limmaDE_EMCI.csv", header = TRUE, row.names = 1)
lmci_de <- read.csv("RP_limmaDE_LMCI.csv", header = TRUE, row.names = 1)
head(emci_de)
head(lmci_de)

       logFC      AveExpr  t         P.Value      adj.P.Val    B
LUC7L3  0.6153943 7.207846  6.963423 4.568928e-11 9.152476e-07 14.694880
KDM6A   0.4644483 4.687607  6.755762 1.484915e-10 1.035676e-06 13.586568
ZMAT1   0.7844973 3.832726  6.748015 1.551032e-10 1.035676e-06 13.545619
HK3    -0.3504250 6.722761 -6.218058 2.840081e-09 9.482085e-06 10.815446
XIST    1.4182019 3.468701  6.074115 6.096700e-09 1.356990e-05 10.099249
PNISR   0.4987351 7.823582  5.976168 1.018552e-08 1.569511e-05  9.618412
       gene_symbol diffexpressed delabel
LUC7L3 LUC7L3      UP            LUC7L3
KDM6A  KDM6A       UP            KDM6A
ZMAT1  ZMAT1       UP            ZMAT1
HK3    HK3         DOWN          HK3
XIST   XIST        UP            XIST
PNISR  PNISR       UP            PNISR

       logFC      AveExpr  t         P.Value      adj.P.Val    B
RPS4Y1 -3.5305596 8.254540 -8.005448 9.362739e-14 7.096772e-10 20.71346
KDM6A   0.6182169 4.557910  7.996819 9.873958e-14 7.096772e-10 20.66254
XIST    1.7408174 3.207370  7.984863 1.062815e-13 7.096772e-10 20.59204
DDX3Y  -1.8641008 4.891695 -7.919837 1.584558e-13 7.302174e-10 20.20954
GPR183  0.5578143 8.068355  7.649303 8.200765e-13 2.053471e-09 18.63559
LTB4R  -0.4931084 6.801345 -7.542765 1.554166e-12 2.830278e-09 18.02374
       gene_symbol diffexpressed delabel
RPS4Y1 RPS4Y1      DOWN          RPS4Y1
KDM6A  KDM6A       UP            KDM6A
XIST   XIST        UP            XIST
DDX3Y  DDX3Y       DOWN          DDX3Y
GPR183 GPR183      UP            GPR183
LTB4R  LTB4R       DOWN          LTB4R

In [3]:
emci_og_geneList <- emci_de$logFC

names(emci_og_geneList) <- row.names(emci_de)

emci_geneList <- sort(emci_og_geneList, decreasing=TRUE)

In [4]:
organism <- "org.Hs.eg.db"

In [ ]:
#png("RP_new_3a.png",width=4800,height=4800, res=600)
set.seed(234)

emci_gse <- gseGO(geneList = emci_geneList,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 5, 
             maxGSSize = 500,
             pvalueCutoff = 0.05, 
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")

require(DOSE)

dotplot(emci_gse, showCategory=5, split=".sign", orderBy = "x", title = "GSEA GO: EMCI subtypes", font.size = 15) + facet_grid(.~.sign)

#dev.off()

In [ ]:
lmci_og_geneList <- lmci_de$logFC

names(lmci_og_geneList) <- row.names(lmci_de)

lmci_geneList <- sort(lmci_og_geneList, decreasing=TRUE)

In [ ]:
#png("RP_new_3d.png",width=4800,height=4800, res=600)
set.seed(234)
lmci_gse <- gseGO(geneList = lmci_geneList,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 3, 
             maxGSSize = 500,
             pvalueCutoff = 0.05, 
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")

require(DOSE)

dotplot(lmci_gse, showCategory=5, split=".sign", orderBy = "x", title = "GSEA GO: LMCI subtypes", font.size = 15) + facet_grid(.~.sign)

#dev.off()

In [ ]:
#png("RP_new_3b.png",width=5600,height=4800, res=600)
p1 = cnetplot(emci_gse, categorySize = "geneNum", foldChange = emci_geneList, showCategory = 5, layout = "gem", node_label="all")

min.value <- floor( min(p1$data$color, na.rm = TRUE) )
max.value <- ceiling( max(p1$data$color, na.rm = TRUE) )

p1 + scale_color_gradientn(name = "fold change",
        colours = c("blue","white","red"), 
        values = rescale(c(min.value, 0, max.value)),
        limits=c(min.value, max.value),
        breaks=c(min.value , 0, max.value) )

#dev.off()

In [ ]:
#png("RP_new_3e.png",width=5600,height=4800, res=600)
p2 = cnetplot(lmci_gse, categorySize = "geneNum", foldChange = lmci_geneList, showCategory = 5, layout = "gem", node_label="all")

min.value <- floor( min(p2$data$color, na.rm = TRUE) )
max.value <- ceiling( max(p2$data$color, na.rm = TRUE) )

p2 + scale_color_gradientn(name = "fold change",
        colours = c("blue","white","red"), 
        values = rescale(c(min.value, 0, max.value)),
        limits=c(min.value, max.value),
        breaks=c(min.value , 0, max.value) )

#dev.off()